### ISSUE TITLE
HW01 README problems

### ISSUE THREAD

**Issue by louiseanne** [mikeizbicki/cmc-csci040#115]
Hi Mike, 
<img width="280" alt="Screen Shot 2021-10-11 at 7 29 41 PM" src="https://user-images.githubusercontent.com/89824785/136882208-764c7307-7be3-4f57-809a-d8f08665cd47.png">

William, Anika, and I are stuck on the screenshots for HW01. Our README.html are rendering as blocks of text in firefox. I included that screenshot of what our files look like. Is that right? Are we on the wrong track? If not, how should we fix this?

**Comment by mikeizbicki** [comment]
The fact that you see both `<>` and `&lt;&gt;` suggests to me that the problem is not in the `compile_code_inline` function like I thought above.

When you typed out your comment above, however, you added spaces between every letter of your output  (you wrote `< p > < b >` instead of `<p><b>`).  In your html file, are there these extra spaces between everything?  If so, you need to figure out where these spaces are coming from and remove them.
