### ISSUE TITLE
Lab_07 original file's encoding issue

### ISSUE THREAD

**Issue by Eddie-Shi** [mikeizbicki/cmc-csci040#134]
![image](https://user-images.githubusercontent.com/89864760/139402234-2f853aa3-f155-4bed-8f22-0495da7df90d.png)
This appears automatically appear when I first downloaded the file from "request". This symbol "âs" seems to be an apostrophe made to be like this due to an encoding issue. What should I do with this?

**Comment by mikeizbicki** [comment]
You're right that this is due to an encoding issue.  The file is encoded in utf-8 online, and so somewhere it got saved in the wrong encoding on your computer.

That's okay, though.  This shouldn't affect any of the text that you have to replace, and you won't be docked any points if you have these encoding errors.

**Comment by Eddie-Shi** [comment]
> You're right that this is due to an encoding issue. The file is encoded in utf-8 online, and so somewhere it got saved in the wrong encoding on your computer.
> 
> That's okay, though. This shouldn't affect any of the text that you have to replace, and you won't be docked any points if you have these encoding errors.

Understood. Thanks a  lot!
