### ISSUE TITLE
hw03

### ISSUE THREAD

**Issue by nataliephillips** [mikeizbicki/cmc-csci040#136]
My items_sold returns null instead of none when there is no information on the amount of items sold. My first line of code happens when I declare itemssold = None, so wouldn't it return None, if there is nothing.

**Comment by mikeizbicki** [comment]
`null` is how json represents python's `None` value, so this is correct behavior.

PS.  In the future, you issue will be more readable if you use markdown's backticks to enclose the code.

**Comment by Vedant11-R** [comment]
I keep getting an 'ebay-dl.py: error: the following arguments are required: search_term' error, even though i am following the same code as you in the video. How do i fix this error

**Comment by mikeizbicki** [comment]
You need to change how you're calling the code on the command line.  You're probably currently doing something like
```
$ python3 ebay-dl.py
```
and this needs to change to something like
```
$ python3 ebay-dl.py hammer
```
I'd recommend focusing on the portions of the video where I'm typing on the terminal to see what I type there and how that changes what happens.

PS.  In the future, use backticks instead of single quotation marks for error messages.

PPS. In the future, you should open a new issue to ask a new question.
