### ISSUE TITLE
hw 03 question 

### ISSUE THREAD

**Issue by Vedant11-R** [mikeizbicki/cmc-csci040#138]
Hey Professor mike, I followed what you had said in the video in the terminal and at the start I was getting the same terminal result as you but when I add the Url (that too exactly how you did) and print it, I get that error (arguements are required) and didnt get the desired url in the terminal

**Comment by mikeizbicki** [comment]
We'll have to meet in person to see exactly what's going on.

PS.  I know that in the previous question #136 I mentioned that new questions should get their own issue created.  In this case, however, it would be better to reply to the previous thread since we already started the conversation there.  Also, I realize these ettiquitte rules can be a bit confusing, and you're certainly not expected to have them mastered at this point.
