### ISSUE TITLE
HW 3 - Alternative Approaches

### ISSUE THREAD

**Issue by HugoMatousek** [mikeizbicki/cmc-csci040#139]
Hello!

I wanted to ask about the possibility of using different approaches/libraries for this task. Namely:

-  using `pandas` and its `DataFrame` instead of the list of dictionaries. I think that it would be more comfortable to work with the data frames, especially if you wanted to list more products (in connection, for example, to having the user chose the number of products).
- using `selenium` to access ebay.com and the data instead of `requests` and `bs4`, alternatively in connection with `pandas` (I have a surprisingly good experience with `pandas` parsing html files with no/little html tags or css selectors, I suppose this will not be the case for ebay.com, but it might be worth a shot). 

Thank you.

**Comment by mikeizbicki** [comment]
You're welcome to use any techniques you'd like for the assignment.

About pandas, I personally don't like it and always avoid it.  It doesn't scale very well to large datasets, and the interface is (IMNSHO) pretty awkward.  The real answer for doing what you're suggesting is a SQL database.  It's much more efficient and powerful.  We'll be covering how to use sqlite in about 3 weeks.

As for selenium:
1. It's significantly slower than requests/bs4 (by at least a factor of 100x).  The reason for this is that selenium actually starts up a firefox webbrowser and processes everything through firefox.  The advantage of selenium is that it helps you avoid scraping countermeasures that some websites take.  Amazon, for example, doesn't want people scraping their product prices since they dynamically change prices based on market conditions, and so the requests/bs4 combo doesn't work but selenium does.
2. There are a variety of ways to specify the location in an html file to extract information, but css selectors are by far the simplest.  Even for projects where I have to use selenium, I would still use css selectors.
