### ISSUE TITLE
Github Page build warning

### ISSUE THREAD

**Issue by HoangChu-Claremont** [mikeizbicki/cmc-csci040#14]
Github emails me this after submitted new changes to my repo:

"The page build completed successfully, but returned the following warning for the `master` branch:

It looks like you're using GitHub Pages to distribute binary files. We strongly suggest that you use releases to ship projects on GitHub. Releases are GitHub's way of packaging and providing software to your users. You can think of it as a replacement to using downloads to provide software. We found the following file(s) which may be a good candidate for releases: test.exe. For more information, see https://docs.github.com/github/administering-a-repository/about-releases.

For information on troubleshooting Jekyll see:
https://docs.github.com/articles/troubleshooting-jekyll-builds"

I've read the docs but don't understand it whatsoever. Anyone knows what's the problem and how to fix it? @mikeizbicki

**Comment by mikeizbicki** [comment]
The warning message refers to the `test.exe` file you have in your repo (which I assume comes from your `test.cpp` file).  It's customary to not include executable files in any github repo, since git is specifically designed to work well for text files.

It's okay to ignore this warning.  If you continue to include these large binary files, you will likely run out of space on GitHub, but I don't think you're anywhere near you limit yet.
