### ISSUE TITLE
HW03 

### ISSUE THREAD

**Issue by milesba4** [mikeizbicki/cmc-csci040#156]
Hey Professor,

I'm having an issue with running my code. All of my doctests work perfectly fine, and my code was working perfectly fine. I closed my file and I'm now getting this error:
<img width="624" alt="Screen Shot 2021-11-09 at 5 24 24 PM" src="https://user-images.githubusercontent.com/90070112/141032505-277282e4-747a-40b8-93bc-2d32e65c2b18.png">

Im not sure what the issue is

**Comment by TjFournier** [comment]
Hey Mike, 

I'm having an issue where it is only downloading the first 5 webpages. After that is no longer adds any items. Everything before that works fine though. Is there anything I can do?

**Comment by mikeizbicki** [comment]
@milesba4  Somewhere in your code, you are running the command `int('385  485')` and that's causing an error because that's not an integer.  Probably that string is contained in a variable, and so you'll have to figure out how that variable is getting created incorrectly.

@TjFournier This is expected behavior.  Ebay is detecting that you're a bot and limiting the number of pages it gives you.
