### ISSUE TITLE
lab I question

### ISSUE THREAD

**Issue by kevinm126** [mikeizbicki/cmc-csci040#160]
Hi mike, Im currently working on the lab and i keep getting the traceback error`prawcore.exceptions.Forbidden: received 403 HTTP response`. Do you know what might be causing this and how i can fix it?

**Comment by mikeizbicki** [comment]
Any error that is between 400-499 means you don't have permission for what you're trying to do.  This is usually caused by not being logged into reddit due to the credentials in the `praw.ini` file not exactly matching what they're supposed to match, and so I'd try double checking that.  There's a few other potential causes that are less likely, but I'd have to see your code 1-1 with you to see if those are problems.
