### ISSUE TITLE
lab-PRAW solution

### ISSUE THREAD

**Issue by zealotwithcharge** [mikeizbicki/cmc-csci040#161]
Hi, Professor! In your post, you said that our solution should look like this
```
========================================
top level comments
========================================
nondeleted_comments= 4
deleted_comments= 2
{Redditor(name='plagiarism-bot'): 1,
 Redditor(name='cs40-bot2'): 2,
 Redditor(name='cs40-bot'): 1}
========================================
all comments
========================================
nondeleted_comments= 735
deleted_comments= 3
{Redditor(name='plagiarism-bot'): 110,
 Redditor(name='sneakpeekbot'): 1,
 Redditor(name='cs40-bot2'): 150,
 Redditor(name='RemindMeBot'): 1,
 Redditor(name='cs40-bot'): 467}
```

But for the "all comments" section, when I add up all the comments made by each of the users, I get 729. (467+150+1+1+110). Is it intentional that the nondeleted_comments is greater than the sum of the individual contributions? I can get my program to output 729 but I'm not sure where I'm missing the other 6. Just off the top of my head, I think your code might be double counting the top-level comments, but if this is intentional please let me know.

**Comment by mikeizbicki** [comment]
You're right!  The answer should be 729, and I've fixed it in the lab.

I originally had a bug in my code.  Rather than actually counting the number of non-deleted comments, I tried to subtract the number of deleted comments from the total number of comments.  I had a typo where I did a `+` instead of a `-` though, causing the bug :/

Thanks for catching this.
