### ISSUE TITLE
Subreddit for our HW/labs banned

### ISSUE THREAD

**Issue by HugoMatousek** [mikeizbicki/cmc-csci040#162]
Hello everyone,

if you have also spent half an hour trying to figure out why is your `monday_secX.py` working just fine and you're getting `403` when doing the lab, then I have some good news for you: it's not (most likely) a mistake on your end. The bad news is that our subreddit got banned.
![image](https://user-images.githubusercontent.com/63810577/141669244-bad11fef-c7b6-419a-ad43-6a1651321ed1.png)

**Comment by mikeizbicki** [comment]
The subreddit is /r/BotTown, not /r/csci40, and is not banned.  See: https://www.reddit.com/r/BotTown/

There was an old version of `bot_stats.py` posted about 2 weeks ago that contained an incorrect URL, and likely you were working with that outdated file.  The current file has the correct URL (along with some additional hints in the comments).

----

PS. Lab attendance has not been great recently.  But these types of issues can get resolved with a real quick 30 second conversation with me in lab rather than having to bang our head against the wall for 30 minutes by yourself trying to figure it out :)

**Comment by HugoMatousek** [comment]
Oh, thank you. I remember the BotTown, but I thought it was a part of the CSCI40 subreddit (clearly, I am not an experienced user of Reddit to know that there are not sub-sub reddits). And I was probably working with an old commit.

I know that this could be probably solved very quickly at a lab - I was very much determined to go there as this is a topic I have not worked with before. Sadly, I did not make it as still deal with some medical problems sometime. At the same time, I think this might be helpful information for anyone who did not make the lab for whatever reason.

Out of curiosity, was the subreddit infiltrated by some outsiders? Or do we know why was it banned (I am asking especially because of the long intro to the HW)?

**Comment by mikeizbicki** [comment]
> Out of curiosity, was the subreddit infiltrated by some outsiders? Or do we know why was it banned (I am asking especially because of the long intro to the HW)?

Reddit went through a wave of banning lots of low profile subreddits last year with no stated reason why.  That particular subreddit is from a 2 year old version of the course, and the subreddit for last year is [/r/cs40temp](https://old.reddit.com/r/csci040temp/), which you can see wasn't banned.  I sent a message to the reddit admins asking why the first one was banned, but they never replied.

PS.  The lab attendance comment was not meant to be directed at you individually, and I certainly do not think less of anyone for a decision not to attend lab for whatever reason.  I just want to generally encourage people to be attending labs in this last portion of the course as the material "weirdness" ramps up considerably.
