### ISSUE TITLE
Lab Question

### ISSUE THREAD

**Issue by jsilva22** [mikeizbicki/cmc-csci040#163]
Hey Mike, when I use pprint for the lab I get ```None``` after using it for each of my dictionaries. This is what I get for example for my all comments section. I know we went over using pprint earlier in the semester but is the ```None``` normal when using it or is there something I can do to get rid of it? Also, should we have our dictionary in the same order as yours or is any order fine as long as we have the correct information? Thanks!
![Screen Shot 2021-11-13 at 11 49 25 PM](https://user-images.githubusercontent.com/90739524/141672439-030bdb2d-86df-426a-a63f-e0fd7ce1fdf4.png)

**Comment by HugoMatousek** [comment]
Hello,
I think that this might be caused by using `print()` to print your `pprint` output. For example, I have tried to replicate your problem:
```
import pprint

test_dic = {'abc':'test','qwe':3}

pp = pprint.PrettyPrinter()

print(pp.pprint(test_dic))
```

This returns:
```
{'abc': 'test', 'qwe': 3}
None
```

The reason is that `pprint` prints the result on its own. If you use it as an argument to `print()` (or even `pprint()`), then your result will be printed by the `pprint()` functions that returns `None` which will be then taken as the input by your other function (and print `None`). It could be some other things, but I think it will be something along the lines of you calling a printing function within a printing function, which results in exactly this behavior.

**Comment by jsilva22** [comment]
Took off the extra print and it worked, thank you!
