### ISSUE TITLE
How long to sleep bot?

### ISSUE THREAD

**Issue by louiseanne** [mikeizbicki/cmc-csci040#170]
How long would you (Mike) or anyone else recommend sleeping the bot.py file while running our bot? I have mine sleeping for 15 seconds now but I'm not sure if that will kick me off eventually, or if I could go any faster. Suggestions?

**Comment by mikeizbicki** [comment]
The most correct thing to do is whenever you get a rate limiting exception, you parse the exception in order to get the number of seconds you need to wait and wait exactly that many seconds.  That would let you get the maximum number of posts the fastest.

An easier thing to do is to just wait 10 minutes, and then you won't trigger the rate limit at all.  There's only 24*60=1440 minutes/day, so that has you making 144 posts/day, so if you run 24 hr/day for 7 days, you'll get 1008 posts.  If there's any bugs or your program crashes for a bit, then you might not have time to get the 1000 post extra credit.

**Comment by nataliephillips** [comment]
How do we show that we have created 1000 comments?

**Comment by mikeizbicki** [comment]
@nataliephillips You will run the `bot_counter.py` command, which displays the number of valid comments.

PS.  In the future, this would be better as it's own issue, since it's not related to the original question.
