### ISSUE TITLE
Extra Credit Option #7 Question

### ISSUE THREAD

**Issue by louiseanne** [mikeizbicki/cmc-csci040#179]
Hi Mike! Quick clarifying question. 

The instructions for extra credit 7 say "Have your bot upvote any comment or submission that mentions your favorite candidate. I recommend creating a separate python file for performing the upvotes, and you must be able to upvote comments contained within any submission in the class subreddit.". 

Is there any set # of comments that we must have upvoted in order to receive this extra credit?

**Comment by sophiahuangg** [comment]
Hi Mike!

This is a follow up to extra credit option 7, but for the textblob sentiment analysis library. The candidate I chose was "Biden", so I want to upvote posts that have a positive sentiment attributed to "Biden." I tried a text that says "Biden is not as good as Trump", expecting a negative polarity, but the result was a positive polarity. Based on the polarity, it upvoted this comment. (I expected it to downvote the comment)

I was wondering if we had to account for this sort of error in our code because can't the sentiment be argued as either good or bad depending on the pov of if you are a Biden or a Trump supporter? Does the textblob library adapt to changing the sentiment given different perspectives? If not, should we just determine our own threshold for the polarity and upvoting/downvoting? (i.e. choosing if we want to upvote the post if the polarity is >0 or if it is >0.1)

**Comment by mikeizbicki** [comment]
@louiseanne You should be upvoting/downvoting ALL the submissions.  There's not that many (much less than comments), and so the script should be able to run in just a few minutes to get everything.  In case there are lots more comments posted, I'll say that you don't need to up/down vote more than 1000 submissions.

@sophiahuangg You're right that there will be lots of errors when using the textblob library.  The library is "noisy" in the sense that on any given piece of text, it won't necessarily get a good polarity, but on average over thousands of texts, it should be doing better than just random guessing.  If you go on to take the data mining class, then you learn how to measure this noisiness formally, reduce it, work around it, and use much more advanced algorithms.  For this class, however, you don't need to do anything special to work around these limitations.  In summary: The fact that you upvoted a comment that you thought you should have downvoted is fine.

**Comment by sophiahuangg** [comment]
Hi Mike, 

I have another question about this one. I'm running my code, but it becomes extremely extremely slow after it upvotes and downvotes a total of around 40 submissions/comments. I've tried rerunning my code and it always pauses at the same number. Do you know if this is a problem with my code or would it be an internet connection issue?

**Comment by mikeizbicki** [comment]
@sophiahuangg This wouldn't be an internet connection issue.  In that case, your code would throw error messages.

Probably what's happening is that the code gets slow when it connects to a submission with many comments inside of it and so when you call `replace_more`, it takes a long time.  If that's the case, then this would be expected behavior.  You can add print statements to see where the code is getting stuck to see if this is in fact the problem, or if it's something else.
