### ISSUE TITLE
2 homework questions

### ISSUE THREAD

**Issue by ohorban** [mikeizbicki/cmc-csci040#18]
For my homework, I am making a photo portfolio, so I am wondering if I can be excused from having to put 3 <p> tags on all of my HTMLs and a list with 3 items?

Also, what is considered to be an "appropriate" alt descriptions for images?

https://ohorban.github.io/

**Comment by brandonsrho57** [comment]
Hey! I can't answer the first question since I'm not Mike, but the "alt" should be included in the img tag: <img src="" alt="">. What the alt tag does is if the image is unreachable or fails to load, it is the associated text that replaces the image such as "Image Not Found" or "Image Can't Be Reached".

**Comment by mikeizbicki** [comment]
@ohorban 

Yes, you can be excused from those two requirements.

An "appropriate" alt tag for the images you have would be a sentence describing what's inside the image.  So, for example, something like "Here's me and my friends at the beach."
