### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by nataliephillips** [mikeizbicki/cmc-csci040#187]
I am receiving an index error with the line: `random.choice(comments_without_replies)`
Is this because it is iterating over a deleted comment? What is the issue? And would adding a try and except clause fix it?

**Comment by zealotwithcharge** [comment]
it might be that your comments_without_replies is empty if there's nothing to reply to and you can't choose from something empty.

**Comment by chatch166** [comment]
Would this be caused by a submission with zero comments? If so, could we get around it by using a try/except statement?

**Comment by kevinm126** [comment]
I was getting this error when I woke up today. I changed my code to catch the error and just output a print statement to tell me that I've already replied to all the comments that are not mine in the submission which is what I'm guessing is happening because if the submission had no replies the bot would just submit its own reply as our has_not_commented variable would output to true.
