### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by jsilva22** [mikeizbicki/cmc-csci040#204]
Hey Mike quick question, for some reason sqlfiddle isn't loading for me. Is there another way to check our practice quizzes?

**Comment by mikeizbicki** [comment]
Yes, you can use the `db_create.py` file to create a SQL database, then the `sqlite3` executable to run a problem's commands and view the output.

You'll need to be careful to delete the database and recreate it after running any `update`/`insert`/`delete` commands, however, since those will permanently modify the database in `sqlite3` (but they don't permanently modify it on sqlfiddle.com).

**Comment by jsilva22** [comment]
Understood thank you! I also tried going to the link you provided to download sqlite3 but I don't see any kind of download, it seems to just be a command we run. Is this correct or is there something we have to download from the download website?

**Comment by yeswetran** [comment]
Yes to what Mike said, but also, there's an easy online alternative to SQLFiddle: [DB Fiddle](https://www.db-fiddle.com/)! Make sure you set it up for sqlite rather than mysql :)
