### ISSUE TITLE
sqlite3.OperationalError Problem

### ISSUE THREAD

**Issue by wgalbreath** [mikeizbicki/cmc-csci040#230]
Hi Mike,

I am experiencing this `sqlite3.OperationalError` in my `project.py` file that just started happening yesterday (even though my website/code was running fine the previous few days). I don't think I changed anything about my code that might've caused it.

![Screen Shot 2021-12-16 at 10 32 24 AM](https://user-images.githubusercontent.com/67754864/146420443-abc7193a-bb20-4f18-9f06-9825511a68a2.png)
![Screen Shot 2021-12-16 at 10 43 35 AM](https://user-images.githubusercontent.com/67754864/146422134-1342d181-3365-4b89-92f4-057513e1f56d.png)

I am not sure if I should just fix this with a `try / except` clause but wanted to see your thoughts since we did not have to do that in class. This error has also shown up on the other lines with `cur.execute(sql)`. Please let me know what you think!

Thank you for your help!
William

**Comment by mikeizbicki** [comment]
The `no such table: users` line indicates that there has never been a `CREATE TABLE users` command run on this database file.  This would happen if you are loading an empty database file that was not created with `db_create.py`.  The most likely cause of this problem is that your paths are messed up, and you need to `cd` into the right folder before running your python commands.
