### ISSUE TITLE
Lab_02

### ISSUE THREAD

**Issue by dwalker25** [mikeizbicki/cmc-csci040#247]
Hi @mikeizbicki,

I'm not sure why my code for the hypotenuse function isn't working, even though it seems straightforward. It looks like it is adding "+0j" for some reason. Here's a screenshot: 
![screenshot_hypotenuse](https://user-images.githubusercontent.com/112443814/190885562-4069d93e-a39b-4154-a1ff-de70243f013a.jpg)

Thanks!
-David

**Comment by dwalker25** [comment]
Similarly, I'm having a problem with my Fibonacci function, even though I've compared it with friends and they are using the exact same code. Not quite sure what the failure is here:
![screenshot_fibonacci](https://user-images.githubusercontent.com/112443814/190885748-161f1895-ddaf-4692-b125-02fe6a1cf547.jpg)

Thanks again! Sorry to double up on the screenshots.
-David

**Comment by justin-is-away** [comment]
Two more quick questions - I think I passed all the tests, since this is the output I'm getting after running the test (no outputs). How would I submit this?

![image](https://user-images.githubusercontent.com/19355638/190885846-5965c1dd-8a16-4a75-89b4-b05b8bf5ddbe.png)

Additional image showing that this command wasn't working at all:

**Comment by mikeizbicki** [comment]
@dwalker25

For the `hypotenuse` function, the example I showed in class was `return (a**2 + b**2)**(0.5)`, which will work.  The `sqrt` function adds the `+0j` term (making the number complex instead of real).

For your `fibonacci` function, you didn't actually show very much output, so I can't say for sure, but I suspect that your `lab.py` file is different than the `lab.py` file that I posted to github.  Likely you copy/pasted the file from github into vscode rather than downloading the file directly, and your computer corrupted the contents during the copy/paste procedure.  If you compare your file to the file on github, I think you'll see that your file is missing some blank lines which are important for the doctests to run correctly.

@justin-is-away 

You need to add the `--verbose` flag after the `-m doctest`.  By default, python will only print the failing doctests (which you have none); to get a summary of all the doctests (both passing and failing) you need to add that `--verbose` flag.

PS.  In the future, you should create a separate issue to ask a separate question.

**Comment by AjaiKBan** [comment]
Good evening @mikeizbicki ,

What does it mean if items have no tests?

**Comment by AjaiKBan** [comment]
Never mind.
