### ISSUE TITLE
Encoding Issues

### ISSUE THREAD

**Issue by ben-smith23** [mikeizbicki/cmc-csci040#266]
Hi Mike,
When I view the html portion of the Dracula lab, there is an issue with encoding and some characters are replaced by question mark symbols, as shown below. I believe this is because some of the characters, such as the apostrophes, are non-standard, since when I type an apostrophe it is slightly different visually than the apostrophes in the original html. Is it ok to submit like this or is there a way to fix it? 

![image](https://user-images.githubusercontent.com/112433581/197310237-4d4859fa-cd7a-4193-9172-d1ca7fff16bf.png)

**Comment by mikeizbicki** [comment]
This will not get full credit as-is, and you're correct that it's due to encoding issues.  The most likely cause of this problem is that you are using the `open` function without specifying the encoding, and your system default happens to not be compatible with this file.  Specifying the encoding should fix it.
