### ISSUE TITLE
No internet connection during Break

### ISSUE THREAD

**Issue by PArellano02** [mikeizbicki/cmc-csci040#286]
I won't have internet connection during thanksgiving break. In the case that I can't run the entirety of the program before then, what do you suggest I do?

**Comment by mikeizbicki** [comment]
You (and everyone else) should finish it before break.  (Breaks are for resting, not for working!)  The recommended due date is this Sunday because I think it is entirely realistic to complete everything by then.

I've only extended the due date past Thanksgiving break because I'm not going to grade it over Thanksgiving break.  (Again... breaks are for resting!)  And so there's no point in me imposing an artificially earlier deadline than when I'm actually going to look at it.
