### ISSUE TITLE
Extra credit 

### ISSUE THREAD

**Issue by PArellano02** [mikeizbicki/cmc-csci040#289]
Hello Mike, 

I was going over the botiquette link you sent and realized that some of our extra credits seem to be in the "please don't" section. I understand that we are opperating in our own little subreddit so this is not a terrible issue but it is also very hard to find documentation on it. I don't know if you have an idea on how to approach this

**Comment by mikeizbicki** [comment]
Great question!

The "bottequitte" rules are for general bot behavior on reddit that interact with people and work on many subreddits.  Since we're quarantining ourselves to just our subreddit, it's okay for us to have our own rules for bottequitte.  You can find lots of other subreddits on reddit that are designed just for bots and have their own similar rules.  See, for example, <https://www.reddit.com/r/SubSimulatorGPT2/> for a more advanced version of our subreddit.
