### ISSUE TITLE
Issue with running file in terminal

### ISSUE THREAD

**Issue by sophiedecastro** [mikeizbicki/cmc-csci040#31]
I'm having a problem with running a file when I try to run just the file name and remove the rest of the path from the terminal. I've followed the instructions from this link: https://stackoverflow.com/questions/43305050/changing-the-default-path-of-visual-studio-codes-integrated-terminal, but it only worked temporarily, and now I'm having the problem again. The error message appears as follows: 

![image](https://user-images.githubusercontent.com/70183987/93514592-63026a00-f8f5-11ea-9d98-e9656646bf2f.png)

When I run it with as:
![image](https://user-images.githubusercontent.com/70183987/93514611-67c71e00-f8f5-11ea-8fb6-6900fecc8903.png)
it runs just fine. 

For reference, this is what my settings currently look like:

![image](https://user-images.githubusercontent.com/70183987/93514492-45350500-f8f5-11ea-8430-a6ad94381284.png)

Any help would be appreciated! Thank you!

**Comment by mikeizbicki** [comment]
Hmmm... the fact that it's resetting every time you load vscode is interesting.  If instead of "opening a file" you choose to "open a folder" and open the folder that contains the `lab.py` file, does that make it work?

Another option is to use the `cd` command in the terminal.  This is something that you would have to do every time you start up vscode, but it's a bit easier once you understand what's going on.  The idea is you would type something like: `cd /Users/SophieD/Documents/Python` in the terminal (it might be slightly different for you, but I think that's it).  You could find out more about the command at this tutorial, which will also provide more background information on what is causing this problem for you: https://www.macworld.com/article/2042378/master-the-command-line-navigating-files-and-folders.html

If neither of those work, I think I'll have to look at this with you over zoom again.

As an aside, this is a very well asked question.  You've included lots of important details which makes it much easier for me to understand exactly what the problem is.

**Comment by sophiedecastro** [comment]
> Hmmm... the fact that it's resetting every time you load vscode is interesting. If instead of "opening a file" you choose to "open a folder" and open the folder that contains the `lab.py` file, does that make it work?
> 
> Another option is to use the `cd` command in the terminal. This is something that you would have to do every time you start up vscode, but it's a bit easier once you understand what's going on. The idea is you would type something like: `cd /Users/SophieD/Documents/Python` in the terminal (it might be slightly different for you, but I think that's it). You could find out more about the command at this tutorial, which will also provide more background information on what is causing this problem for you: https://www.macworld.com/article/2042378/master-the-command-line-navigating-files-and-folders.html
> 
> If neither of those work, I think I'll have to look at this with you over zoom again.
> 
> As an aside, this is a very well asked question. You've included lots of important details which makes it much easier for me to understand exactly what the problem is.

Hi Mike, 

Thanks for your help. The "open a folder" trick didn't work, but the cd command in the terminal did work! I'll keep checking around with other tricks to see what might fix it permanently.

Thanks again,
Sophie
