### ISSUE TITLE
Do anyone know if we have a clue seeing right away if a method applies directly to the object (string, integer, etc) or not?

### ISSUE THREAD

**Issue by HoangChu-Claremont** [mikeizbicki/cmc-csci040#37]

**Comment by brandonsrho57** [comment]
I'm not sure if you're referring to a function (which can take in pretty much anything), but if you use the type() function, you can see what class an object is! So type("Hello World") would return an output of <class str> and type(12) would output <class int>

**Comment by HoangChu-Claremont** [comment]
> I'm not sure if you're referring to a function (which can take in pretty much anything), but if you use the type() function, you can see what class an object is! So type("Hello World") would return an output of and type(12) would output

Thanks for your comment. But what I mean is, for example, let's declare str = 'Hoan':

1. str.append('g') -> str = 'Hoang'
2. str.upper() -> str = 'Hoan'

Both .append() and .upper() are methods of object str, yet one applies changes directly to str, and the other needs a formal attach str = str.upper()

I want to ask if we can remember this attribute difference in Python methods, at least for string-typed objects.

**Comment by mikeizbicki** [comment]
In Python, strings are what is called "immutable", which means that there are no functions that modify a string's value.  @HoangChu-Claremont , your example of `str.append('g')` generates an error because there is no `.append` method.  This is different than lists.  Lists are mutable, and so their values can change, and that is why lists have a `.append` method.

If ever you find yourself wanting to change a string variable in python,
you must follow the pattern of
```
str = str.upper()
```
to generate a new string and assign it the same name.

**Comment by HoangChu-Claremont** [comment]
Gotcha!
