### ISSUE TITLE
pip command not working

### ISSUE THREAD

**Issue by valerialoria** [mikeizbicki/cmc-csci040#44]
Valerias-MBP-2:Data valerialoriaq$ pip install matplotlib
bash: pip: command not found

When I try to run this command to install matplotlib it won't work, did anyone have this issue as well? Any tips on how to fix it?

**Comment by mikeizbicki** [comment]
The command you probably want is `pip3` instead of `pip`.  You may also need to preappend the full path to the python3 command that the triangle button gives you.

This is one of those things that can very quite a bit between computers, so if neither of those things works, we'll have to meet in office hours.

**Comment by valerialoria** [comment]
That worked, thanks!
