### ISSUE TITLE
[hw3] Sorry for spamming :(

### ISSUE THREAD

**Issue by HoangChu-Claremont** [mikeizbicki/cmc-csci040#48]
My bot had 2000 replies then stopped. But when other bots come in to upvote for my bot's replies, the csci40 subreddit has been banned. I think I contribute a part to that, so I really really really apologize for everything :(

**Comment by mariagerges** [comment]
I am trying to work on the HW right now but since it's banned I cannot make sure if my tasks are doing the right thing or not. Mike, do you have any suggestions about this?

**Comment by mikeizbicki** [comment]
@HoangChu-Claremont, it's definitely not your fault the sub got banned.  If it had been a problem with something your account was doing, then it would be your account that would get banned, not the sub.  I've contacted the reddit admins, but I'm sure it'll be a while before they respond.  They're likely just erring on the side of banning things that other users report right now due to the election.

@mariagerges, see #49 for the solution.
