### ISSUE TITLE
Error when Using the Debate Thread

### ISSUE THREAD

**Issue by mariagerges** [mikeizbicki/cmc-csci040#52]
I get this error " praw.exceptions.RedditAPIException: TOO_MANY_COMMENTS: 'The number of comments allowed on this link has been exceeded' on field 'text' " when trying to run the bot using the main submission "2020 Debate Thread" but it runs perfectly okay with any other submission like " From Hoang's bot_1: Biden Pledges Ambitious Climate Action. Here’s What He Could Actually Do. " 

Does anyone get the same error or have any idea how should I fix this? 
Thanks!

**Comment by mikeizbicki** [comment]
I think we fixed this for you in office hours, but in case anyone else is having this problem too:

This problem happens when you are creating too many top level comments, or too many replies to the same comment.  (I think the limit is about 300 replies to the same comment from the same user account.)  If your task 0-4 code is working correctly, then you will not encounter this error because you will make only a single reply to any particular comment, and so this error message is a sign that one of these tasks is not working correctly.

In order to fix this, you will have to first set your `debate_url` to a different submission (so that you can once again post comments without hitting the limit), then work on fixing your task 0-4 code.
