### ISSUE TITLE
[Hw3] When using bot_counter.py, why does my total valid comment seem to be capped at 1000?

### ISSUE THREAD

**Issue by HoangChu-Claremont** [mikeizbicki/cmc-csci040#53]
When my bot adds a reply, its top_level_comment count reduces by 1 and vice versa.

**Comment by dorcassaka** [comment]
I'm having the same issue too @HoangChu-Claremont  where my number of top_level_comment keeps going down.

**Comment by sophiedecastro** [comment]
> I'm having the same issue too @HoangChu-Claremont  where my number of top_level_comment keeps going down. 

I'm having this issue, as well.

**Comment by dorcassaka** [comment]
I talked to Mike and he said that it's because the code only counts newer comments. So after about 1K -2K comments you might notice some counts go down. It just means those comments were older.

**Comment by HoangChu-Claremont** [comment]
> I talked to Mike and he said that it's because the code only counts newer comments. So after about 1K -2K comments you might notice some counts go down. It just means those comments were older.

Yeah that's my guess as well. Can you please ask Mike if we can change the function from new() to top() or hot() ?

**Comment by mikeizbicki** [comment]
I've just checked the reddit API's documentation, and they've revised their API so that you can now only get the 1000 most recent comments.  (It used to be 2000, and that's why the extra credit was set at 2000 comments.)  Based on this, I'm changing the extra credit threshold so that you only need 1000 comments instead of 2000 comments to get the full extra credit.

I think this should fix everyone's concerns, but if there's something that doesn't fix let me know.
