### ISSUE TITLE
Number of Valid-comments decrease

### ISSUE THREAD

**Issue by mariagerges** [mikeizbicki/cmc-csci040#60]
my number of valid comments was increasing until I had 446 valid comments. After this, although I did not change a single thing in my code, the number started decreasing again. This happened two times. Any explanation for this and how should I solve this issue?

**Comment by mikeizbicki** [comment]
This is an indication that something is wrong in your tasks 0-4.  You should
look at the recent comments from your bot on https://reddit.com/u/yourbotname to
figure out why they are not being counted as valid.

**Comment by NilsSkattum** [comment]
having a similar trouble, did you find the error @mariagerges ?!

**Comment by iamclassycain** [comment]
I had a similar issue occur. I was almost at 1000 comments and then the number of valid comments decreased significantly.

**Comment by ohorban** [comment]
same here. I was trying to figure out how valid comments are calculated but it's a little confusing

**Comment by HoangChu-Claremont** [comment]
> I had a similar issue occur. I was almost at 1000 comments and then the number of valid comments decreased significantly.

I think that you should create something to do something with your invalid comments (delete them for example) since your total_comments = invalid_comments + old_valid_comments + new_valid_comments. If your invalid_comments > 0 and invalid_comments + ol_ valid_comments = 1000, more new_valid_comments might be redundant in counting your **total_comments** since Reddit limits counting to 1000 total. Thus, new_valid_comments won't be updated in your total_valid_comments.

**Comment by mariagerges** [comment]
No, I didn't find a solution my number of valid comments seems to be stuck at 500. 

@HoangChu-Claremont I don't think we should edit in the counter file, should we?

**Comment by HoangChu-Claremont** [comment]
> No, I didn't find a solution my number of valid comments seems to be stuck at 500.
> 
> @HoangChu-Claremont I don't think we should edit in the counter file, should we?

Not your counter file, the file is just for counting. My point was you should create a separate function for debugging.
