### ISSUE TITLE
Getting an A/A- in the class

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#68]
Recall that part of the requirements for getting an A or A- in this class was to either read HPMOR or watch several shows.

In order to get credit for completing one of these activities, simply reply to this post with: which activity you completed, and a 1-2 sentence description of your favorite part of the reading/shows.  You should also include your real life name so that I know who to give the credit to.

You have until December 6th to complete this task.

**Comment by sophiedecastro** [comment]
Hey Mike,

This is Sophie de Castro. My favorite show from the screenings was Mr. Robot! I thought the show was really well made, and I liked that it seemed as though one could watch and enjoy the show without any coding knowledge (but I do think the viewer is able to appreciate it more with some knowledge of coding!). One of my favorite storylines from the show is between Elliot and his therapist because I think it includes some of the most “existential” scenes from the show that are especially interesting for the viewer to consider.

**Comment by valerialoria** [comment]
Hey Mike, I am Valeria Loria and I choose to read Harry Potter and the Methods of Rationality. I really enjoyed the book and I thought it was a comical take on both principles of AI and what happens in the actual Harry Potter plot. One of my favorite parts was Ch. 10 Self Awareness, Part II where Harry is having a conversation with the Sorting Hat while he is being sorted. I thought it a was very clever to have Harry "blackmail" the hat into doing what he wanted, but I also thought there was a very interesting idea when they made reference to the hat being/or becoming conscious, like AI machines! I also thought that it was a nice twist to put Harry in Ravenclaw. 

I also want to share this with everyone, its a Ghostbusters parody using lyrics from HP. This is from Ch. 11 

(As performed on the kazoo by Fred and George Weasley,
and sung by Lee Jordan.)
.
There's a Dark Lord near?
Got no need to fear
Who you gonna call?

"HARRY POTTER!" shouted Lee Jordan, and the Weasley twins performed a triumphant chorus.

With a Killing Curse?
Well it could be worse.
Who you gonna call?

"HARRY POTTER!" There were a lot more voices shouting it this time.

**Comment by HoangChu-Claremont** [comment]
I'm Hoang Chu and I love reading Harry Potter and the Methods of Rationality. It’s creative, funny, intense, emotional, and continually pushed me to want more. This story also makes me think about intellectual property and copyright lengths again. Harry Potter and the Methods of Rationality is perhaps the best example I’ve ever seen of someone creating an incredible story in a world that they didn’t have IP rights to, and it makes me wonder how many more stories like this could exist if copyright lengths were shorter.

**Comment by mariagerges** [comment]
Hey, mike This is Maria Gerges. I completed the second option (watching the movies and the shows.) The one I liked the most was Zero Days. I usually like documentaries more than movies and shows but this one was even more exceptional. I have always wondered about how did it all start and why do viruses exist if people internationally make them!! This was so confusing for me and the documentary helped me answering these questions and provided me with historical context and background information. I have never heard of Zero Days before so I definitely learned something new from the documentary. I also like how it engages hackers from both genders and from different cultures and different backgrounds. I also liked the quote that said " it's not about if, i's about when." I really enjoyed watching this documentary!!

**Comment by yilinli22** [comment]
Hi Mike. This is Yilin Li, and I read Harry Potter and the Methods of Rationality. This book really builds a second world that is consistent, logical and reasonable. It explains a lot of concepts that are helpful to answer the question "How does magic really work". I especially love how the book explains the concepts of Bayesian updating.

**Comment by ktzchen** [comment]
Hey Mike, this is Katie Chen, and I chose to watch the shows you recommended. One of the most impactful scene that stood out to me was definitely in the first episode when Elliot hacks his therapist. The scene shows how Elliot, based on simple conversations with his therapist and his general knowledge of her, was able to procure things like her computer password. It also shows how much information we leave online and the illusion of privacy we have. If someone really wanted to, they could find out a lot of information about us. It definitely made me more aware of my digital footprint.

**Comment by brandonsrho57** [comment]
**Hey Mike!** This is Brandon Rho! I chose to watch the shows that you listed~ My favorite *by far* has been *Mr. Robot*, mostly because it's realistic scenes and attention to detail when it came to how cyber-security worked in real life! I actually liked it so much that I've moved on to the second season (out of 4!) My favorite scene from season 1 definitely has to be when: it's revealed to us that Elliot is Mr. Robot himself! The earlier portions of the show made so much more sense, and turned the show in a new direction!

**Comment by joellemin** [comment]
Hi Mike! This is Joelle Min! I decided to watch some of the shows that you listed on the syllabus. My favorite show was Mr. Robot! The twists, amazing acting, and culturally relevant plot kept me hooked the entire season. As a whole, the show serves as a critique of corporate power and corruption within the political and economic systems of our society. I was initially drawn to the show because I am a fan of Rami Malek, but one of my favorite scenes has to be the opening scene. Elliot is introduced with his encounter at Ron's coffee shop. After seeing the end scene and how his "dad was the only person [he] could talk to," the opening scene introduces viewers to a much brighter Elliot. The actor who played Ron had an amazing performance as I felt like I was in the scene when his life was crumbling before his eyes as Elliot exposed him. Because the producers introduced Elliot as a vigilante hacker, it portrays his work as a force for good and a transformative power over corruption.

**Comment by sarahfreeman-star** [comment]
Hi Mike! This is Sarah Freeman! I watched the shows that you listed. I particularly enjoyed watching the documentary, Zero Days. This documentary was very good at explaining what Zero Days are. This documentary was a wake-up call for me about the extent of the dangers of the cyberworld. It is scary that our physical safety can be hacked. Cyberweapons like Stuxnet (the first one entirely made of code) have the power to switch off oil pipelines and turn up the pressure inside nuclear reactors. Stuxnet also has the power to fool the operators into thinking that everything is normal when it's not. This documentary brought up an interesting ethical question: Are the hackers who sell security leaks morally responsible for what their customers do with it? I think all hackers need to make sure they are using code ethically. Yes, it is not their responsibility what others do with it since they limited control over that. There is no guarantee that your exploit will only be used for certain things. However, they should have the common sense to not send them to sketchy individuals and third parties.  I believe it was Hans Folmer who made the insightful comment about cybersecurity that "offense is easy; defense is hard." It is so easy to be a bad person. We all have a capacity for evil and a capacity for good. The most common one is that many hackers are tempted to do malicious things if they are paid well for doing it. Another scary thing I discovered was that a little mistake in code can lead to more serious ones, and we don’t have a way of predicting how these mistakes will affect us. It is all so unpredictable. We usually won’t even know what went wrong, but we can only hope that there is no chain reaction.

**Comment by NilsSkattum** [comment]
Hey Mike, this is Nils Skattum. I watched the shows and the movies you listed. Zero Days offered a cool insight into a world I had known very little about. What struck me about the idea of white-hat, gray-hat, and black-hat hackers is how much of a social experiment the world of hacking and ethics can be. Considering how international these players are, government oversight is not a given (especially considering governments seems to lack the knowledge and skill-set sufficient to constantly defend against high-level hackers). Although the documentary alludes to the Dutch government's work to protect Dutch interests, it's very clear from the footage from the expo how "free" the market and market players are for zero days and other attacking and defensive software. This means that we are all currently in an age where people, on a daily basis, are choosing whether to hurt or protect others. While I am sure the debate rages on whether or not those who provide cyberweapons are really hurting others, to me the link seems rather clear. 

In CitizenFour, I found Edward Snowden a more likeable and courageous character than I had previously believed. I realized how much of my perspective had been skewed by media. What he accomplished is historically relevant and on a scale few people realize. I think as current US government investigations into large-scale media and tech firms continues, it is people like Edward Snowden who need to be behind the scenes directing politicians in the correct way to frame questions and ensure the private sector can be kept in check. Of course, seismic changes need to occur in the government itself in order to then address the private sector's abuse of power. What was particularly striking about this movie was how little I knew about everything going on in. I grew up in England and understood British surveillance was something of the most intrusive in the world but did not realize the true extent. What scares me is that because it's such a technical and complex world, the general public's understanding is severely limited. Humans can comprehend the destruction caused by a missile or a bullet. They can see a factory building those things. The same cannot be said of the cyberweapons world and I think that will increasingly become a dangerous reality. 

I thought Mr. Robot was fantastic. I think watching the two documentaries first allowed me to see how true the show was to the world discussed in Zero Days. The connection and constant presence of companies like E Corp are also an interesting theme that I believe lends to the increasing lack of clarity and transparency of tech firms and other companies. 

Finally, I really enjoyed War Games. This was mainly because I like Matthew Broderick and enjoyed seeing him in a role other than as Ferris Bueller. 

A recommendation from Netflix: The Social Dilemma

**Comment by mel088** [comment]
Hi Mike! This is Melanie Williams and I watched the four shows you listed. I enjoyed watching all of them but I enjoyed watching Mr. Robot the most. I found it entertaining that Elliot is an unreliable narrator and a skilled hacker. I also liked that Elliot referred to the conglomerate E-Corp as “Evil Corp”.

P.S. If you are interested in another movie about the Snowden story, I recommend watching the movie Snowden!

**Comment by saneenkhan** [comment]
Hi Mike! My name is Saneen and I read Harry Potter and the Methods of Rationality. As someone who loves Harry Potter, I really enjoyed reading the book and seeing how the author was able to change the story and explain the scientific method. I particularly enjoyed the chapters on the Stanford Prison Experiment. I particularly appreciated these chapters because they showed us a lot about Harry's train of thought and his rational thinkinbg. Also, I was just really interested to see how they were going to play out because there were a lot of surprises. I also found the dynamic between Harry, Draco, and Hermione quite entertaining. HPMOR really surprised me because I never imagined such a creative way to explain scientific concepts. 

A quote I enjoyed/found amusing:
"It was the most insanely Gryffindor thing Harry had ever..." (ch.55)

**Comment by tkapoor22** [comment]
Hi Mike, this is Tanya Kapoor! I really enjoyed reading Harry Potter and the Methods of Rationality. I’m a huge fan of the series, so it was nice to enter the Potter world again. One of my favorite chapters from the book was Chapter 22 based on The Scientific Method. As a biology student, I have often had to design experiments for labs and reading about Harry’s frustrations of testing a hypothesis and designing an experiment is something that I can closely relate to. Another one of my favorite chapters was Chapter 70 based on self-realization. I really liked Hermione’s simple definition of a hero, someone who does the right thing over and over again even if they are scared. A hero’s primary goal is to do the right thing, which often becomes something extraordinary and not the other way round. Overall, I really liked how the author, Eliezer Yudkowsky, was able to explain technical concepts in a fun and humorous way. I also loved that the book had many alternate plot lines and story twists that I did not expect. 

Some quotes that I loved: 
- "Mmm... okay," said Hermione. "But I was also hoping for something like 'Hermione's books aren't worthless. They're written by wise old wizards who know way more about magic than I do. I should pay attention to what Hermione's books say.' Can we have that moral too?"

- Hermione took a couple of deep breaths, trying to be brave. "It's not about being not ordinary," she said as stoutly as she could. "But I think if someone just tries to do what's right, over and over again, and they're not too lazy to do all the work it takes, and they think about what they're doing, and they're brave enough to do it even when they're scared -" Hermione paused for an instant, her eyes darting to Tracey and Daphne, "- and they cleverly plan how to do it - and they don't just do what other people do - then I think someone like that would already get into enough trouble."

**Comment by willwaaang** [comment]
Hi Mike, 

I'm Will Wang and I've chosen to watch the show/movies about hacking for the A/A- in the course. Mr. Robot, in particular, is a show that I've already watched prior to this class, and thus, I may be biased in saying that it was my favorite out of the bunch. My favorite scene from the first season of the show occurs at the end of episode 8, where Elliot finds CDs that contain old family photos. The revelation in the scene—which I won't spoil—really blew me away, and the soundtrack was especially memorable.

**Comment by refe22** [comment]
Hi Mike,
This is Ruth Efe. I read _Harry Potter and the Methods of Rationality_. I can confidently say I have never read anything like it before. I did appreciate how the story was interwoven with references to different fields of study (sciences, psychology, economics, etc.). Although there were more than I could name or recognize, I loved the reference to Robbers Cave in Chapter 9, the Prisoner's Dilemma in Chapter 12, and the use of the Stanford Prison Experiment for Chapters 52 to 63. I also like the self-reflexivity of the book; there were many comments that poked fun or dismissed the rationality of the common things we find in storybooks/fictional media. My favorite quotes about this would be from Chapter 80 and Chapter 81:

> "Only in Disney movies were ugly people more likely to be evil and vice versa; and those movies were probably scripted by writers who'd never been ugly." 
-Ch 80
> "It didn't say anything like what he thought Hermione was feeling, faces couldn't say anything that complicated, all facial muscles could do was contort themselves into knots.' 
- Ch 81

I didn't like Harry's attitude to be honest. He constantly under-estimates other types of intelligence besides books smarts and fails to notice how the ability to be rational requires the full realization of all information (that information is perfect and complete) which is rarely realistic. As an economics major, it was interesting to read about a character that is the common assumption in economics: that people are rational. But this would have to be my favorite quote about Harry:

> "He hadn't realised how shaky his hope had been, until he'd noticed how surprised he'd been after the hope had come true. Sometimes things did go better than expected. And Harry took that thought, too, and put it into the magic he was building."
- Ch 115

This was in stark contrast with how Harry was at the beginning of the story when he was telling Professor McGonagall that it is better to assume the worst possible outcomes. 
We love character development!

**Comment by iamclassycain** [comment]
Hi Mike,

This is **Robert**. My favorite piece from the screenings was Mr. Robot. I found the show extremely engaging, and I really enjoyed watching it because I would never click on this show otherwise. My favorite part from season 1 was watching Elliot hack the man who was dating his therapist. While this scene was a bit unsettling to watch, it was also a reminder that our personal data is never truly secure.

**Comment by dorcassaka** [comment]
Hi Mike! This is Dorcas Saka, and I chose to watch the screenings. I enjoyed the documentary ***Zero Days- Security Leaks for Scale*** the most. The documentary was well made, and I enjoyed learning about the ‘white-hat’ hackers versus the ‘black-hat’ hackers. The word hacker often has a negative connotation, so it was great to learn about hackers who are trying to protect people and grassroots organizations like **I Am The Cavalry.** One thing I do find interesting is that a lot of these bugs and security threats often are not reported to the general public. For example, I never heard of Stuxnet until watching the documentary.

**Comment by nickwilson3** [comment]
Hi Mike, this is Nick Wilson and I chose to watch the first season of Mr. Robot. I really enjoyed this show because growing up I watched a lot of superhero shows, so this was similar in the sense that there is a "good guy" and a "bad guy", however instead of physical violence and super strength, the "good guy" used coding. My favorite part of the show was when Elliot first stopped fsociety's cyber hack in the beginning because that reminded me of those intense scenes in superhero shows.

**Comment by samcbogen** [comment]
Hello Mike, this is **Sam Bogen**, and I watched the four selections: Mr. Robot (Season 1), War Games, CitizenFour, and Zero Days. Predictably, I enjoyed Mr. Robot and War Games the most, and I did particularly enjoy Mr. Robot to the point that I will probably watch Season 2 on Amazon Prime over winter break. Honestly, thank you for having us watch it, I thoroughly enjoyed the show. 

One of my favorite scenes was actually one of the first of the show -- in Episode 1 when Elliot confronts Ron at Ron's coffee shop. This is where we first meet Elliot, and the second time that I had to do a double-take and say, "wow, Rami Malek is an amazing actor" (I had seen Bohemian Rhapsody and was blown away by him there too). Beyond Malek's acting chops, despite how early it is in the season, it really is a great window into Elliot's character, and a moment that got me hooked on the show.

**Comment by ohorban** [comment]
Hi, this is Oleksandr (Alex) Horban. I've watched Mr. Robot (Season 1), War Games, CitizenFour, and Zero Days. Mr Robot and WarGames were my favorite. I also started watching the second season of Mr robot but the first episode wasn't that engaging.  I would definitely recommend WarGames to others. I like how it pictures the world before cybersecurity became a thing.

**Comment by smccann11** [comment]
Hi Mike, this is Spencer McCann. I watched Mr. Robot (Season 1), War Games, CitizenFour, and Zero Days.

I was particularly intrigued with both CitizenFour and Zero days and their underlying themes of ethical and unethical hacking. In regards to Snowden, whether or not you think that surveillance of that scale is necessary is up to public debate, but Snowden himself thought it to be of his best interest to expose the data. In regards to Zero days, it amazed me how little ethical reasoning went into the sale of zero days. In both cases it was rather surprising how much gray area there is when dealing with cyber security and its possible threats from a legal perspective.

**Comment by adien43** [comment]
Hi Mike, 
For the extra credit I decided to watch Mr. Robot, War Games, CitizenFour and Zero Days. 
My favorite was Mr. Robot as I am a fan of Rami Malek. The best scene I think is when he realizes that Mr. Robot is not real and tries to accept the circumstances. I thought this show eluded to many digital uses and issues with the world today.

**Comment by marielacenteno** [comment]
Hi Mike! 
This is Mariela Centeno. This semester, I decided to watch the shows and movies. Even though I’m a huge fan of Mr. Robot, I found Zero Days extremely fascinating. Before this class, I didn’t really understand the magnitude of technology in its political context, but through my newly found coding background and through this documentary, I’ve been able to actually grasp some of the dangers and benefits that come with technology in today’s political environment. To me, the most interesting part of the documentary was how it described global malware attacks as a “world war fought with ones and zeros.” The specific example of the first physically dangerous virus, Stuxnet, really surprised me as it was used as a tool to inhibit Iran’s nuclear enrichment facilities, something that is still a prevalent issue in today’s politics. This documentary really reinforced the idea that technology is interdisciplinary and has a very large influence in the world.

**Comment by ZacDavis0-159910538** [comment]
Hi Mike, This is Zac.
I read Harry Potter and the Methods of Rationality. As someone who writes fantasy I greatly appreciated the balance between scientific rationality and magical fantasy. Specifically, I found the rational lens through which Harry interprets everything to be interesting such as in Chapter 2 when he attempts to use a scientific experiment to prove the existence of magic or in Chapter 3 when he learns of Voldemort and compares it too metallurgy. 

> "“Voldemort?” Harry whispered. It should have been funny, but itwasn’t. The name burned with a cold feeling, ruthlessness, diamond clarity, a hammer of pure titanium descending upon an anvil of yielding flesh. A chill swept over Harry even as he pronounced the word, and he resolved then and there to use safer terms like You-Know-Who."

I also enjoyed Harry's different perspective in general to the characters around him particularly his debates with magical characters such as this quote from Chapter 7.

> “No, Draco, that’s not it, don’t you see? Science taps the power of human understanding to look at the world and figure out how it works. It
can’t fail without humanity itself failing. Your magic could turn off, and
you would hate that, but you would still be you. You would still be alive
to regret it. But because science rests upon my human intelligence, it is
the power that cannot be removed from me without removing me. Even
if the laws of the universe change on me, so that all my knowledge is void,
I’ll just figure out the new laws, as has been done before. It’s not a Muggle
thing, it’s a human thing, it just refines and trains the power you use every
time you look at something you don’t understand and ask ‘Why?’ You’re
of Slytherin, Draco, don’t you see the implication?”
I also loved the continual asides by the Author against the original plot of Harry Potter, whether it be questioning why certain things worked, rewriting and questioning certain scenes or future plot devises, or changing character relationships such as Ron and Harry. 
Additionally, with the author sidesteping some of Harry Potters major issues, I liked the way Harry handled Snape, although I'm also glad they restricted the time turner because he felt overreliant on it in early scenes in ways that seemed clever but often ended up not being so.

**Comment by Skyler-Bradley** [comment]
I watched Zero Hour, the Snowden live action movie as well as the documentary, I read Harry Potter's Methods of Rationality, and watched the first season of Mr. Robot. I definitely liked Mr Robot the most of them all. I really liked when (it was either episode 1 or episode 2) they showed a very realistic portrayal of a DDOS attack on a computer security firm's server. The executive of the company asks "where does the attack come from" showing a little technical knowledge, but the main character, Elliot, who is a lot faster with understanding the scale of the attack and how computers work responds something like "Thailand, India, Sweden, everywhere, obviously." The show even shows how he has to fly to the server building himself and connect his laptop using the Linux system to override the attack. Everything in the show is very accurate and you can pause on the scenes where Elliot is on a terminal to see the exact Linux commands and paths he uses.
