### ISSUE TITLE
Required reading / viewing

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#79]
Recall that in order to earn a grade that is at least an A- in this class, you must either read a *Harry Potter and the Methods of Rationality* or watch a handful of videos. (Details and links are in the syllabus.)

In order to get credit for having completed this assignment, you should reply to this post with a 2-3 sentence description of your favorite part of the reading/viewing.

**Comment by KaranGoel1** [comment]
I completed the second task as well. One of the most interesting parts that stood out to me was how accessible hacking is, seeing a 17 year old hacking his own government systems. It was also interesting to see how at events such as DefCon, hackers from all backgrounds and ethics (black market hackers present too) come together to discuss the next steps and inventions in hacking. One thing that Zero days taught me to be aware of is how connected everything is, and the very real possibility of software causing physical danger to people, especially with the advent of self driving cars or neural chips being developed by Elon Musk. It certainly opened my eyes to how vulnerable everyone is to a potential super virus/malware that could cause large scale damage.

**Comment by aaryanb1** [comment]
I also completed the second task. My favorite part was realizing how complex and scary the cybersecurity world is. Unbeknownst to many people, these zero-day exploits are being sold to governments, companies, and criminals whether for good or bad. I found it interesting how the government cannot really protect us from these exploits (as seen with the ending), and all we can do is update our systems, not use them at all, etc. Moreover, I found it scary how our anti-viruses can only stop known exploits, but not unknown exploits, so things can go horrible whether for an individual or a highly-automated society very suddenly and quickly.

**Comment by HugoMatousek** [comment]
I am in the process of watching the videos (while I love reading, Harry Potter is not my favorite, and while the fan-fiction can be better, I am not giving it a chance due to its length). I will update the comment as finish the different sub-tasks.

i) Mr. Robot
I quite liked the show. At the same time, I think it's one of the things that you sort of need to binge watch. Otherwise, you'll soon lose track of what is real, what is now, and who is who. 'Evil Corp.' as the villain is a bit of a exaggeration as its monopoly power is unreal. At the same time, when it comes to hacking, I think the show does a good job! Where it fails is sometimes the personal hacking (the Steele Mountain part is just such a long shot and some things make zero sense there). I also found a couple continuity issues but that might be related to the plot twist (which I, btw, managed to figure out about 4 episodes before its reveal). Also, I loved the StarGate/Pulp Fiction reference.

ii) War Games
You can tell the movie is from 1983. But that's just fine. It's lovely. The level of AI _Joshua_ has is obviously unreal. At the same time, I liked the hacking at the beginning of the movie + seeing the Cheyenne Mountain complex brought up some good memories!

iii) CitizenFour
not started

iv) Zero Days
not started

**Comment by nikhilagarwal1111** [comment]
I completed the second task and watched the Zero Days documentary. There were two aspects of the documentary that really stood out to me, the first one being the relationship between the digital world and the physical world, and how these two world are slowly becoming integrated. Most people likely think that hacking merely takes place in the cyber world, and has no real world, tangible impact on the physical world, but as the documentary pointed out, important pillars of society such as hospitals and power lines are now capable of being fully shut down by hackers with bad intent. Secondly, the advent of hacking has now made it such that world wars are now being fought online by national governments, even if it seems on the surface that defence forces which engage in conventional warfare are at peace with each other. I found this interesting because it raises questions as to what a real cyber World War might look like, who would come out, and how such a war would affect our society and international order

**Comment by derikkk** [comment]
I decided to complete the second task. My favorite part was definitely Zero Days. To me, the documentary highlighted two important aspects. Firstly was how countries (the US mainly) used Stuxnet to achieve their political agendas. Although the US temporarily achieved its objective of slowing down the development of Iran's nuclear program, their actions set the precedent for the possibility of cyber warfare. Adding onto this issue, due to the 'wall of secrecy' that surrounds such topics, the press, public, and countries cannot engage in debate surrounding these issues. Without conversation, common understanding and global standards regarding cyber warfare cannot be made- leaving us in a perilous position.

**Comment by swen7589** [comment]
I completed the second task (watching films) and my favorite part was Citizen Four. I was so surprised at how easy and how often the government invades people's privacy for "the greater good". I truly understand why Snowden did what he did, because to be forced to work against his own morals and self-interest is quite demanding mentally.

**Comment by Eddie-Shi** [comment]
Although I've decided to complete the second task, I did read parts of the *Harry Potter and the Methods of Rationality*:the “interdict of Merlin” and the prophecy “the dark lord will mark him as his own” was met when Voldemort gave Hariezer the same grade he himself had received. It was quite a "trippy" experience, even if I didn't finish it.

Speaking of grade- my favorite three works are *Citizen Four", *WarGames*, and *Mr. Robot*- the grade-changing scene in WarGames reminded me of my fantasy of reality manipulation (to change the grade- I know, it's silly) back when I was in elementary school. It was simply a chuckle. In addition, I also appreciate that *WarGames* was on the more realistic side in computer science, such as the usage of dial-up Internet access and it did not show hacking as a person typing nonsense rapidly, ending with the catchphrase "I'm in". Moreover, the film was actually ahead of its time by mentioning the military application of Artificial Intelligence and the realization of vivid Machine Leaning. It was "fun" and "interesting" to say the least.

For Citizen Four, privacy intrusion from individuals, NGOs, and the governments (state and federal) has always been present since the birth of the country, worsened during the Cold War. Mr. Snow's exposé of the doings were brave, but also the "well-known secret" by everyone.

Finally, the big one- *Mr. Robot Season 1* was truly a feast. As reviewed by many critics and anecdotes from programmers, it was the most realistic representation of hacking anywhere in the history of media- in particular, the description of honeypotting, doxing, how hacker groups actually communicate within, and etc. Furthermore, it was not only a geeky technology drama but also a critic of capitalism and how technology, the supposed means of progress for humanity, turned into a tool solely for money-making.

In conclusion, it was a blast :D.

**Comment by evankim08** [comment]
I completed the second option, which is watching a handful of videos. My favorite part of the viewings was definitely Mr. Robot. Although only the first season of Mr. Robot was required viewing, I am a few episodes away from finishing the second season because of how much I enjoyed the first one. Although clearly the show is dramatized, it is fascinating to watch how entire corporations, from its security to its data, are built on programs. As such, there can be bugs that can be exploited. My favorite part from Season 1 was when Elliot talks about daemons, and relates them to the real lives of people. He says:

"Daemons perform action without user interaction. Monitoring, logging, notifications, primal urges, repressed memories, unconscious habits. You can try to be right, you can try to be good, you can try to make a difference. But it's all bullshit. 'Cause intentions are irrelevant. They don't drive us, daemons do. "

In general, I find it very interesting how programming can be compared with the dynamics of daily life.

**Comment by abroegger8** [comment]
I completed the second task, which entailed watching a variety of shows/movies about hacking. My favorite part of this task was definitely watching Snowden played by Joseph Gordon-Levitt. I have always been a big fan of biopic movies, such as American Sniper and Captain Phillips, so Snowden is the type of movie I thoroughly enjoy watching. Growing up in Hong Kong, I remember following the news when Snowden was on the run there. It was really interesting to see his experiences unfold in the city I call home. Furthermore, I think the movie was highly engaging because it portrayed a good balance of Snowden's personal life and career. It was highly informative and I felt like Snowden's character was well developed in the movie. I also liked how he wasn't portrayed as a villain, which allowed for the audience to develop their own perceptions on whether he is a hero or villain. Finally, my favorite scene in the movie was definitely when he escapes the NSA facility with highly classified information hidden in a rubik's cube (I wonder if this actually happened or not).

**Comment by mikeizbicki** [comment]
@abroegger8 

>Finally, my favorite scene in the movie was definitely when he escapes the NSA facility with highly classified information hidden in a rubik's cube (I wonder if this actually happened or not).

Snowden collaborated with the producers of the movie when making this film, and in his memoir he states this is actually how he smuggled the material out: <https://www.pilotonline.com/entertainment/books/vp-db-book-edward-snowden-20190917-y7b54jrmabgdbmlwmvl7ccu6ga-story.html>.

**Comment by christinakulick** [comment]
I completed the second task for this assignment. My favorite part of all the viewings was definitely watching Mr. Robot. It was a show I did not think I was going to enjoy, but it was very captivating. The most interesting part for me was looking at the interaction between human emotion and hiding behind hacking/computer programs. While Elliot always tried to stay hidden in the shadows when it came to interactions (such as with his dad) he grew very emotional and was unable to act as he normally would behind the computer screen. I also loved seeing the power of what hacking and computer science could accomplish in society and how much it can affect businesses and those who work within them. Another scary part was how easily accessible all of what we do on our computers is and I don't think about that on a daily basis. Thanks for showing us this show Professor!

**Comment by nathanarimilli** [comment]
I also completed the second task which was to watch multiple shows about hacking and cybersecurity. I found the War Games movie very fascinating and I was impressed with how well this movie was produced and directed for 1983. I also was surprised that this movie covered the topics of artificial intelligence and machine learning in relation to the military. Although this movie is fictional, after watching Zero Days, the possibility and threat of something like War Games happening seems  more possible as the digital world and physical reality are slowly converging. Moreover, as things become more operated and controlled by software powered machines, the damage that can occur from cyber attacks and leaks could be devastating and extremely dangerous.

**Comment by louiseanne** [comment]
I completed the second task as well. Of the videos assigned, I found the documentary Citizen Four the most interesting. I didn't know much about the Snowden leaks, as they happened when I was younger, and this documentary put into perspective the issues for me. It was interesting as well to see how 'paranoid' Snowden was about privacy, for example with the blanket he put over his head when entering passwords, and unplugging the phone. I think the idea of working with classified documents, and dealing with sensitive information, has always made sense to me but I've never thought about what that means for the personal, every day activities of those who handle it. 

Zero Days also made an impression on me, of course because of its content about malware and cyber attacks, but also because of the people they interviewed. I knew that computer science was a largely white and male dominated field, but seeing just how elite some hackers are (the group of roughly 1000), and then the fact that one woman was interviewed, and one to two people of color, was a little shocking to me. I know that wasn't the point of the documentary, but I left thinking about how necessary more diversity is needed especially in this field where there can be such an 'elite' group of hackers at the top.

**Comment by zealotwithcharge** [comment]
I completed the second task. The documentary Citizen Four was quite scary and made me think of other moral implications specifically in AI. It seems that AI will become ever more prevalent in our lives. As such, if governments are able to get hold of powerful AIs, it seems that state power will become too powerful for the people to reasonably fight back, exactly like what Snowden feared with the technical prowess of the NSA.

Zero Days again made me think of AI. Considering that AI is able to code these days, I was imagining a coding AI and a hacking AI. The hacking AI will try to hack the coding AI's code and the coding AI will learn from these attempts and create more secure code. This is similar to a chess AI playing itself over and over again to get better at chess. I wonder if such a thing would be possible. However, one problem I see from such an AI could be that it becomes impossible for humans to interpret the AI's code. In these cases, it would be hard to verify that the AI only created code that it was asked to create.

**Comment by nilavenkat** [comment]
I completed the second task of watching the movies and TV show. My favorite part of this task was definitely watching Citizen Four. It was shocking to see how easy it is for the government to invade our cyber privacy, even if citizens aren't doing anything wrong. While it was slightly amusing at first to see the extents that Snowden went to in order to protect his privacy, it made me reconsider the way I engage online. It also contextualized a lot of the privacy protecting measures Mike does (like not having a cell phone), which I admit was baffling to me at first, but makes total sense after watching this documentary.

**Comment by milesba4** [comment]
I completed the second task. I really enjoyed watching Snowden and found the scene where Snowden was tasked with creating leverage over Marwin by fishing for information on his personal relations to be a great lesson on how cruel privacy invasion practices can be. I had already watched season 1 of Mr.Robot before this taking course, and my favorite scene from season 1 is when Elliot cracks his therapist's social media password. I am more appreciative of this scene after completing the cracking lab

**Comment by NACB** [comment]
I completed the second task. I liked all of them, although out of the 4, *War Games* was probably my least favorite. *Mr. Robot* was interesting enough for me to want to watch the next couple seasons, and the more realistic hacking was a nice touch especially after gaining some background knowledge through the class. That being said I started watching it expecting it to be just about hacking, so there was a lot more schizophrenia and recreational morphine use than I expected. *Citizen Four* really expanded my perspective on the scope of NSA surveillance, and the *Zero Days* documentary taught me about a whole economy I didn't even know existed. Worthwhile stuff.

**Comment by yeswetran** [comment]
In _CitizenFour_, when one of the journalists asked Edward Snowden why he decided to blow the whistle on the NSA, Snowden replied, "I remember what the Internet was like before it was being watched, and there's never been anything in the history of man that's like it." That concept of a free-as-in-freedom pre-9/11 Internet really stuck with me throughout my viewings. Along with _CitizenFour_, _Mr. Robot_ and _Zero Days_ both portray the Internet as a dark web where greed, realpolitik, and paranoia reign supreme. However, _WarGames_ troubles me too, because it accentuates that the Internet, even in its earliest, most theoretical stages, has always experienced tremendous involvement and influence from the military-industrial complex. Either way, I'm glad that I watched these four pieces, and I'm even more glad that this class deepened my thinking about the Internet and its future.

**Comment by qchen2323** [comment]
I completed the second task. My favorite one was *CitizenFour*. Edward Snowden was brave enough to blow the whistle on the massive covert surveillance programs run by the NSA and other intelligence agencies, even though he knew that this will put his life at stake. The documentary was exceptional and raised an important question about power and privacy. The documentary made me become more aware of my use of technology.

**Comment by shreyachatterjee22** [comment]
I completed the first task by reading the Harry Potter fan fiction (reading is always faster to me that watching a movie) and found the experience really interesting. While Harry was a supremely more pragmatic character in the fan fiction whose interjections I didn't always appreciate, likely because it didn't match my idea of the flow of the original book, I learned a lot from his character, including how to be a wizard hedge fund millionaire. The sorting scene was one of my favorites because neither the original books or the movies explore in depth an aspect of the magical world that is so integral its social structure. Finally, my favorite quote comes from Prof. McGonagall who tells Harry that "You triumphed over the Dark Lord by being more awful than he was, and survived the Killing Curse by being more terrible than Death." Perfectly captured her original sarcasm.

**Comment by nrj-demello** [comment]
I finished the second task. I particularly enjoyed watching _WarGames_. Not only did the "hacking" not seem exaggerated, like in many other movies, but it was interesting to read the thread about the movie that underlines how realistic the programming was. It was especially intriguing to understand how dial-up internet access worked, as I was not aware that back then computers were connected to landlines. I also enjoyed the movie as it is placed in the context of heightened tensions of the 1980s during the cold war, which is directly linked to a history course I'm taking this semester: Cold War America.

**Comment by herbertlohmus** [comment]
I completed the second task. I liked all of the videos/movies/series/documentaries, however Mr.Robot and Citizen Four were my favorite. In Mr.Robot I really liked the parallel between real hacking and social engineering, which also uses exploits and rules of human nature to lead to a wanted outcome. Furthermore the idea of just using a simple computer such as the Raspberry pie connected to the thermal control system to destroy everyone's data shows how cheap and easy it really is to create chaos and unrest if you have motivated person with the right set of skills.  In citizen four what stuck with me the most was a statement made in the last few minutes of the documentary of how the concept of liberty has evolved and turned into the idea of privacy, which thanks to Snowden seems to point to the complete lack of. I don't know how I feel about it exactly as although I am aware that I am constantly being watched, ive come to accept the fact of the matter.

**Comment by jennifersjlim** [comment]
I completed the second task. My favorite part of the viewing was Snowden. Having prior knowledge about the story of Edward Snowden, watching the movie was relatively easier for me to follow. The scene that really pulled me in was the one where Snowden was given his first task from the CIA. What intrigued me was the words of Corbin who explains that the purpose of such tasks are to prevent America from suffering the next 9.11 that may happen anywhere (online). These words along with the following plots of the movie on whistleblowing really got me thinking about the ethical standards that such agencies must abide by as issues of privacy invasion occurred regardless of its original intentions. Although Snowden's story is well known to the public, watching the movie made me ask myself questions on the thin line between precautions and ethics.

**Comment by NHendelman** [comment]
I completed task #2. My favorite viewings were Zero Days and Citizen Four. Zero days made me think about how the future of war and national security has moved from actual fighting to digital surveillance. Digital warfare is the future and it’s as scary as real war.
Citizen Four made me really question our existing government structure and the trust I place in it. We are all aware that our data is being stored but I always seem surprised to find out the extent. It’s also really surprising that the legal system is so stacked against Snowden. With what Snowden was charged, it doesn’t matter if the U.S. intelligence agencies’ surveillance is illegal in the first place or his revealing documents are in the public interest. Crazy! I was happy to find Snowden is not in jail today.

**Comment by chatch166** [comment]
I completed task two, the viewing activities. Some of my favorite moments were the scenes in Mr. Robot where _fsociety_ was describing how their encryption method was staying offline, instead of sophisticated security online, or when Elliot is fixing the bug in the server farm. It was interesting to see those two poles of tech security: either humming banks of complicated servers or normal offline life. 

Another highlight was _Snowden_: I thought it was interesting to see how his hopes around internet privacy rose and fell with shifts in presidential administrations, it goes to show the extent of seemingly controversial and politically unstable programs that actually can go untouched across administrations because people don't know/don't care about them. 

Finally, and more generally, I appreciated the the alternate definitions of hacking on display in several of the movies. Mike is always telling us that to hack is to build, not destroy, so it was cool to see that play out on the screen.

**Comment by jaceycarter** [comment]
I completed the second task! I enjoyed all the videos; however, Mr. Robot was my favorite and War Games were a close second. While Mr. Robot portrayed the Internet and programming as dark and deceiving, War Games portrayed the internet and programming as something that can do good for the world.

In Mr. Robot, it was nice to have background in programming to understand what was happening during the episodes. It was cool to see Elliot work professionally by day but do his "hacking" at night which is similar to us calling this course "intro to hacking". It was interesting how the original CTO of the company had no knowledge regarding tech and because of his ignorance, he ended up getting taken advantage of. This could be the case in major companies today! Like they always say... it's about who you know! I though War Games contrasted this dark image of Elliot. David on the other hand was young, innocent, and naive!

**Comment by AChiu42** [comment]
I chose to do the second task, which was to watch Mr. Robot, War Games, Citizen Four, and Zero Days. While I found all of the films to be very enjoyable, the one movie that stood out to me was Zero Days, as it really opened my eyes to the dangers and prevalence of hacking. I always thought I understood what the terms black market and white market meant, but lacked the fundamental understanding of these concepts. Zero Days further illustrated to me how connected everything is by the internet; additionally, it also opened my eyes to how easy it is for anyone to gain access and “hack” other people.

**Comment by jhwang22** [comment]
For the required reading / viewing, I chose to read the Harry Potter fan fiction. What I liked most about the reading was seeing numerous - and very clever - references to social and cognitive psychology. (Love to see those as a psychology major). One good example comes from Chapter 6, titled “The Planning Fallacy”, which refers to people’s tendency to to underestimate the time it will take to complete a task. Essentially, we tend to be overly optimistic, and Harry does take the right measures to combat this bias by being (though his explanation of the solution was pretty dry, not going to lie). Anyway, that was an interesting way of adding tension to the story, especially since we learn at the end of the chapter that McGonagall believes Voldemort is still alive, and there’s a prophecy involving him and Harry. 

Overall, kudos to Less Wrong for giving a riveting and highly educational written piece.

**Comment by laurenleadbetter** [comment]
I chose to complete the second task and watched the movies and Mr.Robot. Mr.Robot was my favorite primarily because of the character Angela. Despite her personal troubles with monogamy and work/life balance I empathize with her struggles in the workplace. Angela had to deal with a lot of misogyny and sexism that contributed to making E-Corp look like a bad and evil corporation, but these scenes hit close to home as this sort of corporate culture has felt overwhelmingly common at companies I previously thought were fine.
My second favorite viewing was Citizenfour. Previously, I had heard a lot about Snowden and his leaks, but never fully understood who he was or why his actions were getting so much attention. I found the plot of Citizenfour compelling, and after I looked up ‘Citizenfour vs. reality’ overviews. I was surprised to see how accurate the documentary was, making me fond of Laura Poitras, for her work with Snowden and on the documentary.

**Comment by josiahtarrant** [comment]
I just finished task two. My favorite two shows/movies about hacking were Snowden and Zero Days. Before watching Snowden, I did not have a full understanding of what his whistle-blowing was all about (probably since I was younger when I first learned about it). Watching the film gave me a new perspective on our government and how much data is really being collected. Also, as someone who likes to have some philosophical conversations, I enjoyed watching as he weighed what was morally right and wrong. 

I liked Zero Days because it gave me another new perspective on software and the role it plays in our safety. I did not realize how important it was for companies and governments to continuously be thinking about safety as they launch new software in order to avoid leaks/threats. I also found it very interesting how the documentary talked about governments not being able to guarantee our safety and needing to rely on young hackers instead.

**Comment by nataliephillips** [comment]
I completed the second task. My favorite part of the second task was Mr. Robot because I had watched the first season before I took this class and really didn't understand any of the hacker jargon. Going through the second time with Mr. Robot was so interesting to see how the injected programming talk that would pass right over regular viewers head. It really shows how Mr. Robot catered to two different audiences.  I also would join in the praise of its technical aspects, in terms of being semi realistic. The other movies were interesting in how they depicted hacking and that realm differently; however, I thoroughly enjoyed seeing how much of Mr. Robot's "hacking-easter-eggs" went over my head the first time around.

**Comment by anikakimme** [comment]
I completed the second task as well. My two favorite shows/movies from the task were Zero Days and CitizenFour. I enjoyed watching Zero Days because I had very little previous knowledge about the topic beforehand. Learning about the ethics of hacking and the white, grey, and black market was interesting since everything is legal despite ethical considerations. Additionally, it was interesting to learn about the high demand of hackers capable of finding complex zero days in all of the markets. According to the documentary, while tens of thousands of people can find web vulnerabilities, one in 1000 people can bypass platform-wide shields and less than half are willing and capable to work with the good guys.

CitizenFour was the most surprising to me. Although I was alive when the Snowden leaks happened, it was interesting to learn more about the actual details of what was going on. At the beginning of the documentary I didn’t realize the huge risk Snowden had taken to expose all the privacy breeches happening within the government and the government had to citizens' information, even those who were not seen as high risk. However, as the documentary continued it was clear the huge risk that Snowden had put himself at and how dire the consequences were that he was willing to undertake. I definitely learned a lot about whistleblowing and privacy policy on the federal level from CitizenFour.

**Comment by TjFournier** [comment]
I completed the second task. I think the most interesting one for me was War Games, mainly because of the personal aspect. While I enjoyed the rest of shows/movies I had a pre-CS view on War Games since I grew up watching it because of my dad. I remember the first time I saw it I thought, "That RTS game looks terrible compared to Command and Conquer" and "The user interface looks terrible" but now I truly appreciate the front end development since I suck at it.

**Comment by DienAlex** [comment]
I completed the second task, watching Mr.Robot, War Games, CitizenFour, and Zero Days. My favorite one out of the four is the Mr. Robot which I went onto season 2 due to the cliffhanger at the end of the season. I really enjoyed all the little coding easter eggs such as the naming of the episodes littered throughout the entire show. CitizenFour is next in line as the most interesting mainly because I had previously heard of Snowden before and remembered how it was a big deal back then. It was most shocking to me to see how much Snowden risked to expose what's happening within the government and to protect private information. I felt that what he did is respectable as he put down his entire life, his family, his job, just to protect citizens' information. The last two I was least interested in but I still enjoyed viewing and watching each of them. War Games was entertaining to watch while Zero Days was extremely informative and I learned a lot about white, grey, and black hat hacking. Overall, these viewings were useful videos/movies that are both entertaining and informative.

**Comment by kevinm126** [comment]
I completed the second task where we watched videos and series. My favorite part was watching Mr.Robot. The show opened my eyes up to a different point of view of cracking and gave real world importance to things we did in class by showing how cracking can be so dangerous. It also opened my eyes up to how dark it can get when people who are good coders decided to crack peoples personal information.

**Comment by Vedant11-R** [comment]
I decided to do the latter task. I watched  war games and the war dial lab at the same time, which made me believe that I was in war games. Usually movies about hacking per se are very unrealistic, a person types on a computer for two minutes and suddenly has the nukes In Russia under their control. This movie had a very realistic portrayal, however the most fascinating aspect about this movie was the fact that it was made in 1983. Such a great production, and such insightful aspects of A.I in a movie which was made in 1983 is truly remarkable. 

I would watch movies like Central Intelligence, where the US government could hack into any system, but again the display was so unrealistic I never understood the reality of it. After watching Citizen Four I have concluded that the government can easily hack into any space and a truly encrypted medium is a myth.

**Comment by Jblachman** [comment]
>
My favorite takeaway from Citizenfour was putting a face, voice, and perspective from Snowden himself.  Over the years I have read many articles and heard perspectives from many powerful people.  To hear Snowden’s talk about the reasons behind his actions was stimulating.  My only criticism was that it was a little romanticized and twisted into a favorable narrative for Snowden.  

Even though War Games is such an old film, I found myself enjoying it greatly.  Growing up in Seattle, I enjoyed David’s character (I wish I could’ve changed some of my grades in high school).  Watching someone that young doing such significant hacking captured my interest.  The tic-tac-toe solution made me smile that something so simple was so important in a world war.

I already watch the first season of Mr. Robot a few years ago, so it didn’t take away any new surprises.  I think my favorite part of it all is seeing someone with mental health issues be the focal point of the show.

**Comment by janetcen** [comment]
I chose to complete the second task for this assignment. Out of all the viewings that we had to watch, my favorite has to be Citizenfour. This documentary stuck out to me the most because I remember hearing about Snowden before, but I never really took the time to look into what had happened. But since this semester, I've been a lot more interested in computer ethics.

My favorite scenes have to be of the interview footage of Snowden as he talked about his perspective and motives behind what he did. It's inspiring to hear about just how committed he is to protect people's privacy and their freedom to access whatever they desire. I also enjoyed how the director, Laura Poitras, chose to tell the story. Showing the ripple effect of Snowden's actions through all different perspectives (oooh politics..).

**Comment by keirkeenan** [comment]
1. Season 1 of Mr. Robot - My favorite part of _Mr. Robot_ was Mr. Robot's monologue about how far society is from the true reality. He hinted at how the marketing, advertising, and technologies of large corporations (like E Corp) guide public opinion and shape our thoughts to fit their needs. It's an interesting perspective to see media as a sort of fake reality, and also see through the season how susceptible people are to exposing their private information.
2. War Games - What I most enjoyed about War Games was how the story embodies the hacker way of being lazy and curious. It was great watching David jump from something as personal as hacking the school district's computers and changing his and his friends' grades to finding games that connected him to Soviet missile simulations. It also amazed me how the film connected war automation to video games, showing how technology can make each happen at the click of a button.
3. CitizenFour - I had seen clips of Snowden before and also watched _Snowden_ not too long ago, so this documentary really helped me understand where Snowden was coming from in his decision to leak sensitive information. I really enjoyed hearing how important it was for Snowden to let the public know of the NSA's illegal wiretapping practices, while also recognizing that he was putting himself at risk of treason.
4. Zero Days - I really enjoyed learning about the different areas of hacking, namely white, grey, and black hat hacking. It amazed me how legal many of the practices are, and that most of the discussion is centered on the ethics of hacking tactics.

**Comment by kimsngmin00** [comment]
I also completed the second task for this assignment. My favorite video was Zero Days since I enjoy watching documentary films in general. The part that stood out to me was the existence of a “grey” hat hacking - I’ve known that there are “white” hat hackers and “black” hat hackers but I didn’t know that there was a grey area in between them. This helped me understand that destructive codes and security codes both develop and change rapidly over years, leading to the hackers’ more comprehensive perspective of the society. Also, the way they described Stuxnet reminded me of how our Reddit bots attacked(?) other bots, replying to any and all comment that is made.

**Comment by leynahong** [comment]
I completed the second task, and my favorite viewing was Mr. Robot. Overall, the show was incredibly well-made. The plot was very entertaining as we followed Elliot through his struggles with both his mental health and his anger with the world. It was very thought-provoking and made me reflect a lot on our current world of technology and the direction it is heading. On one hand, I am excited about how many opportunities technology can open up for us, but Mr. Robot showcases many dark realities about the world of technology and the disruption it can cause. 

I was also very drawn to the characters, particularly Elliot. While he was obviously socially awkward, he was extremely intelligent, both mentally and emotionally, and it was very easy to like him and be invested in his story.

**Comment by nzhang30** [comment]
I completed the second task of watching videos regarding hacking. I would say my favorite videos were Snowdon and Mr. Robot. My favorite part of Snowden is the ethical challenge that is posed to Edward Snowden, of choosing to release classified information regarding the tracking of communications. I think the discussion resulting from this film is very important in the current day and age, given how personal data is being exploited. It further offered perspective on the experience of a whistleblower, and highlights the US’s stance towards espionage. Zero Days discussed the role of ethics in hacking, and also was a great reminder of the pitfall of technology, that everyone is vulnerable as a result the world’s interconnectedness. 

Mr. Robot was also a very interesting show. During my post-watch research it was exciting to learn that the “hacking” shown in the show is relatively accurate to similar real world events. In comparison to shows like the matrix, other mainstream movies (where hacking is typing keys), it was very enlightening to see what it would look like in reality. Elliots character development was also very intriguing, and mixed with the overarching goal of destroying Evil Corp, I think that Mr. Robot was one of the best shows I’ve watched

**Comment by macroanton** [comment]
When watching the first couple episodes of Mr.Robot for the second task, it was fascinating to see a coders ethical code clash with dark realities. Albeit dramatized for entertainment, watching Elliot grapple with his own internal struggles and those who violate his perspective of justice felt as though the show was reshaping the vigilante troupe to address the tech concerns other streams of media shy away from. 

I also appreciated seeing Joey Bada$$ in the show.
