### ISSUE TITLE
Tutor contact info

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#8]
@gPlacide and @benfig1127, can you both reply to this message with instructions for how cs40 students who want tutoring should contact you?

**Comment by benfig1127** [comment]
To meet with me, students should schedule an appointment on the qcl webpage, 
```
[Link](https://www.cmc.edu/qcl) 
```
Then simply scroll down towards schedule an appointment and you can browse to my name with my availability by each day. Alternatively you can also filter by my name or by CS 40. Finally, if my listed schedule does not work for you I can usually find time to meet with you on an ad hoc basis. Simply send me an email at bfigueroa20@students.claremontmckenna.edu. 

Look forward to working with everyone! 🤙

**Comment by gPlacide** [comment]
I'll share the zoom link and the times that I'll be available tomorrow. If anyone needs help in the meantime, feel free to send me an email at pgatabazi21@cmc.edu

**Comment by gPlacide** [comment]
As promised, this is the recurring Zoom info for my tutoring hours. It's set for Thursdays and Fridays from 1 PM to 3 PM PST. I chose those hours because it seems that that's when Ben is not around. I do not have a Zoom Premium account, therefore, I might have to work with one person at a time. 

**If those times do not work for you please email me and we can find a time that works for both of us**

[Zoom Link](https://zoom.us/j/96714686657?pwd=YXpDclZLWC9BMnYyQ1FTWWsrMTNIQT09)
Meeting ID: 967 1468 6657
Passcode: 4PBdyw

**Comment by gPlacide** [comment]
Starting tutoring hours at 1:30 pm today.

**Comment by gPlacide** [comment]
I'm moving my today's tutoring hours to 4 pm PST. If you can't make it at that time send me an email and we will find some other time that works for both of us even if it's in the weekend.

**Comment by mikeizbicki** [comment]
I'm granting a 48-hour extension on the lab (until Tuesday midnight) for anyone who meets with the tutors this week.  Just let me know and I won't count your assignment late.

The concepts we've reviewed this week (functions/if statements/loops) form the foundation for everything we'll be doing in python, and so it's super important to make sure you get any questions about these concepts answered.

**Comment by gPlacide** [comment]
I'm sorry but I have to push my tutoring hours to 330 pm pst today. As always send me an email and we can schedule sometime in the weekend to meet.
