### ISSUE TITLE
SyntaxError: invalid syntax (likely not from the code) 

### ISSUE THREAD

**Issue by derikkk** [mikeizbicki/cmc-csci040#99]
Hi Mike, #
<img width="600" alt="Screen Shot 2021-09-17 at 11 29 17 AM" src="https://user-images.githubusercontent.com/89935741/133836784-53f692f7-8fc8-4c55-b307-9d866cb50767.png">

I'm working with Adrian and encountered some syntax error issues which prevent me from testing. We went through the code to see if I missed something (ie. a colon or a space) but we couldn't find any errors there. Is there anything I could try to fix this? Thank you. 

Derik

**Comment by Tonnpo** [comment]
Hi Derik,

It would be great if you could provide more information on steps to reproduce the error you have. These could be, but not limited to,

1. Sharing your code so that we are able to identify all possibilities to the cause of your error
2. Sharing the commands you have run i.e. `python  blah.py`

These will help others to potentially check why something might not be working properly. Moreover, in later, if you post issues on other open source projects, having as much as detailed that others can follow will increase the chances that your questions will get answered. 

Hope this helps!

Ton

**Comment by mikeizbicki** [comment]
The problem is that your terminal window is no longer in terminal mode but in something called "interactive python mode".  Pressing CTRL+C or CTRL+D (possibly many times) will fix it for some computers; for other computers, closing and reopening VSCode will fix it; for other computers, you can type `exit()` after the `>>> `.

If none of those options work, restarting the computer should reset things.

**Comment by derikkk** [comment]
Thanks for your help Mike! Have a great weekend!
